# Generated by Django 3.2.6 on 2021-08-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
