# Generated by Django 3.2.6 on 2021-09-03 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
